web:
  image: nginx:latest
  ports:
    - "8080:80"
  volumes:
    - ./code:/code
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php

php:
  build: .
  volumes: 
    - ./code:/code
  environment:
    XDEBUG_CONFIG: remote_host=host.docker.internal
  links:
    - mysql

mysql:
  image: mysql:latest
  ports:
    - "3306:3306"
  environment: 
    - MYSQL_ROOT_PASSWORD=foo
    - MYSQL_USER=lebrett
    - MYSQL_PASSWORD=foo
    - MYSQL_DATABASE=gatci

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - mysql:db
  ports:
    - "8082:80"
  environment:
    - PMA_USER=lebrett
    - PMA_PASSWORD=foo
    - PHP_UPLOAD_MAX_FILESIZE=100MB
